### ISSUE TITLE
Tests fail in master

### ISSUE THREAD

**Issue by abrahamq** [urbanriskmap/cognicity-schema#13]
Dropping the cognicity schema, running ./build/run.sh and then running the tests (npm test) causes 2 tests to fail: 

` 
5 passing (199ms)
  2 failing

  1) CogniCity Schema Functions GRASP Reports Schema Functions Correctly pushes the report to all_reports table:

      Uncaught AssertionError: 0 must be equivalent to 1
      + expected - actual

      -0
      +1

      at ValueAsserter.is (node_modules/unit.js/src/assertions.js:56:20)
      at null.<anonymous> (test/testCognicitySchema.js:147:42)
      at Query.handleReadyForQuery (node_modules/pg/lib/query.js:114:10)
      at null.<anonymous> (node_modules/pg/lib/client.js:172:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:121:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)

  2) CogniCity Schema Functions GRASP Reports Schema Functions Correctly issues a notify when card received status is set to true:
     Uncaught SyntaxError: Unexpected end of input
      at Object.parse (native)
      at null.<anonymous> (test/testCognicitySchema.js:171:29)
      at null.<anonymous> (node_modules/pg/lib/client.js:153:12)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:121:12)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:523:20)
`

**Comment by abrahamq** [comment]
huh I dropped the db, ran run.sh again and it was still happening. Did it one more time and now the tests pass?
