### ISSUE TITLE
1 test failing in Bengaluru

### ISSUE THREAD

**Issue by ojha-url** [urbanriskmap/cognicity-schema#59]
Floodgauge report schema functionality: Bengaluru
{ error: more than one row returned by a subquery used as an expression
    at Connection.parseE (/Users/apple/Github/cognicity-schema/node_modules/pg/lib/connection.js:54
6:11)
    at Connection.parseMessage (/Users/apple/Github/cognicity-schema/node_modules/pg/lib/connection
.js:371:19)

    at Socket.<anonymous> (/Users/apple/Github/cognicity-schema/node_modules/pg/lib/connection.js:1
14:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
  name: 'error',
  length: 666,
  severity: 'ERROR',
  code: '21000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'SQL statement "UPDATE floodgauge.reports\n        SET tags = (SELECT \'{"instance_region_
code":"\' || COALESCE(code.code, \'null\') || \'", \'|| \'"local_area_id":"\' || COALESCE(la.pkey::
varchar, \'null\') ||\'"}\' FROM (SELECT (SELECT code FROM cognicity.instance_regions AS i WHERE ST
_WITHIN(NEW.the_geom, i.the_geom))) AS code, (SELECT (SELECT pkey FROM cognicity.local_areas as j W
HERE ST_WITHIN(NEW.the_geom, j.the_geom))) AS la)::json\n        WHERE pkey = NEW.pkey"\nPL/pgSQL f
unction floodgauge.define_report_region() line 3 at SQL statement',
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'nodeSubplan.c',
  line: '1036',
  routine: 'ExecSetParamPlan' }
    1) "before all" hook: Insert dummy floodgauge data

**Comment by abrahamq** [comment]
What branch is this off of?

**Comment by abrahamq** [comment]
This was caused by overlapping instance regions. Mayank added a test to make sure that doesn't happen in the future.
